/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2022-11-01 06:43:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.register;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register05_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1666247059660L));
    _jspx_dependants.put("jar:file:/C:/eclipse-jee-2020-06-R-win32-x86_64/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springProj/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   $(function() {\r\n");
      out.write("      $(\"#aSubmit\").on(\"click\", function() {\r\n");
      out.write("         $(\"#frm\").submit();\r\n");
      out.write("      });\r\n");
      out.write("      $(\"#marriaged\").on(\"click\", function() {\r\n");
      out.write("         let chkYn = $(\"#marriaged\").is(\":checked\");\r\n");
      out.write("\r\n");
      out.write("         if (chkYn) {\r\n");
      out.write("            $(\"#marriaged\").val(\"true\");\r\n");
      out.write("         } else {\r\n");
      out.write("            $(\"#marriaged\").val(\"false\");\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   $(function() {\r\n");
      out.write("      $(\"#btnZipCode\").on(\r\n");
      out.write("            \"click\",\r\n");
      out.write("            function() {\r\n");
      out.write("               new daum.Postcode({\r\n");
      out.write("                  oncomplete : function(data) {\r\n");
      out.write("                     //zipCode\r\n");
      out.write("                     $(\"input[name='addressVO.postCode']\").val(\r\n");
      out.write("                           data.zonecode); //우편번호5자리\r\n");
      out.write("                     //addressName\r\n");
      out.write("                     $(\"input[name='addressVO.address']\").val(\r\n");
      out.write("                           data.address); //주소\r\n");
      out.write("                     //addressDetail\r\n");
      out.write("                     $(\"input[name='addressVO.addressDetail']\").val(\r\n");
      out.write("                           data.buildingName); //상세 주소\r\n");
      out.write("                  }\r\n");
      out.write("               }).open();\r\n");
      out.write("            });\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"card shadow mb-4\">\r\n");
      out.write("   <!-- Card Header - Accordion -->\r\n");
      out.write("   <a href=\"#collapseCardExample\" class=\"d-block card-header py-3\"\r\n");
      out.write("      data-toggle=\"collapse\" role=\"button\" aria-expanded=\"true\"\r\n");
      out.write("      aria-controls=\"collapseCardExample\">\r\n");
      out.write("      <h6 class=\"m-0 font-weight-bold text-primary\">Collapsable Card\r\n");
      out.write("         Example</h6>\r\n");
      out.write("   </a>\r\n");
      out.write("   <!-- Card Content - Collapse -->\r\n");
      out.write("   <div class=\"collapse show\" id=\"collapseCardExample\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("         <form id=\"frm\" action=\"/register/register05\" method=\"post\">\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("               <label for=\"exampleFormControlInput1\" class=\"form-label\">userId\r\n");
      out.write("               </label> <input type=\"text\" class=\"form-control\" name=\"userId\" id=\"userId\"\r\n");
      out.write("                  placeholder=\"userId\" value=\"a001\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("               <label for=\"exampleFormControlInput1\" class=\"form-label\">password\r\n");
      out.write("               </label> <input type=\"text\" class=\"form-control\" name=\"password\"\r\n");
      out.write("                  id=\"password\" placeholder=\"password\" value=\"java\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("               <label for=\"exampleFormControlInput1\" class=\"form-label\">coin\r\n");
      out.write("               </label> <input type=\"text\" class=\"form-control\" name=\"coin\" id=\"coin\"\r\n");
      out.write("                  placeholder=\"coin\" value=\"100\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("               <label for=\"exampleFormControlInput1\" class=\"form-label\">birth\r\n");
      out.write("               </label> <input type=\"date\" class=\"form-control\" name=\"birth\" id=\"birth\"\r\n");
      out.write("                  placeholder=\"birth\" value=\"2022-11-01\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("               <label for=\"exampleFormControlInput1\" class=\"form-label\">gender</label>\r\n");
      out.write("               <p>\r\n");
      out.write("               <div class=\"form-check form-check-inline\">\r\n");
      out.write("                  <input class=\"form-check-input\" type=\"radio\" name=\"gender\"\r\n");
      out.write("                     id=\"gender1\" value=\"male\"> <label\r\n");
      out.write("                     class=\"form-check-label\" for=\"gender1\">Male</label>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"form-check form-check-inline\">\r\n");
      out.write("                  <input class=\"form-check-input\" type=\"radio\" name=\"gender\"\r\n");
      out.write("                     id=\"gender2\" value=\"female\" checked> <label\r\n");
      out.write("                     class=\"form-check-label\" for=\"gender2\">Female</label>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"form-check form-check-inline\">\r\n");
      out.write("                  <input class=\"form-check-input\" type=\"radio\" name=\"gender\"\r\n");
      out.write("                     id=\"gender3\" value=\"other\"> <label\r\n");
      out.write("                     class=\"form-check-label\" for=\"gender3\">Other</label>\r\n");
      out.write("               </div>\r\n");
      out.write("               </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("               <label for=\"exampleFormControlTextarea1\" class=\"form-label\">nationality</label>\r\n");
      out.write("               <p>\r\n");
      out.write("                  <select name=\"nationality\" class=\"form-select\" aria-label=\"Default select example\">\r\n");
      out.write("                    <option selected>Select your nation</option>\r\n");
      out.write("                    <option value=\"korea\" selected>대한민국</option>\r\n");
      out.write("                    <option value=\"america\">미국</option>\r\n");
      out.write("                    <option value=\"australia\">호주</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("               </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("               <label for=\"exampleFormControlInput1\" class=\"form-label\">cars</label>\r\n");
      out.write("               <p>\r\n");
      out.write("                  <select name=\"cars\" class=\"form-select\" multiple\r\n");
      out.write("                     aria-label=\"multiple select example\">\r\n");
      out.write("                     <option selected>Select your cars</option>\r\n");
      out.write("                     <option value=\"K5\">K5</option>\r\n");
      out.write("                     <option value=\"QM6\">QM6</option>\r\n");
      out.write("                     <option value=\"Audi\">Audi</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("               </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("               <label for=\"exampleFormControlInput1\" class=\"form-label\">hobbys</label>\r\n");
      out.write("               <p>\r\n");
      out.write("               <div class=\"form-check form-check-inline\">\r\n");
      out.write("                  <input class=\"form-check-input\" type=\"checkbox\" name=\"hobbyList\"\r\n");
      out.write("                     id=\"hobbyList1\" value=\"footsal\"> <label\r\n");
      out.write("                     class=\"form-check-label\" for=\"hobbyList1\">footsal</label>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"form-check form-check-inline\">\r\n");
      out.write("                  <input class=\"form-check-input\" type=\"checkbox\" name=\"hobbyList\"\r\n");
      out.write("                     id=\"hobbyList2\" value=\"movie\"> <label\r\n");
      out.write("                     class=\"form-check-label\" for=\"hobbyList2\">movie</label>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"form-check form-check-inline\">\r\n");
      out.write("                  <input class=\"form-check-input\" type=\"checkbox\" name=\"hobbyList\"\r\n");
      out.write("                     id=\"hobbyList3\" value=\"drama\"> <label\r\n");
      out.write("                     class=\"form-check-label\" for=\"hobbyList3\">drama</label>\r\n");
      out.write("               </div>\r\n");
      out.write("               </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("               <label for=\"exampleFormControlInput1\" class=\"form-label\">marriaged</label>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("               <input class=\"form-check-input\" type=\"checkbox\" name=\"marriaged\"\r\n");
      out.write("                  id=\"marriaged\" value=\"false\" autocomplete=\"off\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("               <label for=\"exampleFormControlInput1\" class=\"form-label\">address</label>\r\n");
      out.write("               <div class=\"p-5\">\r\n");
      out.write("                  <div class=\"form-group row\">\r\n");
      out.write("                     <div class=\"col-sm-6 mb-3 mb-sm-0\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control form-control-user\"\r\n");
      out.write("                           name=\"addressVO.postCode\" id=\"postCode\" placeholder=\"postCode\"\r\n");
      out.write("                           value=\"915\" />\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <a href=\"#\" id=\"btnZipCode\" class=\"btn btn-info btn-icon-split\">\r\n");
      out.write("                        <span class=\"icon text-white-50\"> <i\r\n");
      out.write("                           class=\"fas fa-info-circle\"></i>\r\n");
      out.write("                     </span> <span class=\"text\">Search For PostCode</span>\r\n");
      out.write("                     </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                     <input type=\"email\" class=\"form-control form-control-user\"\r\n");
      out.write("                        name=\"addressVO.address\" id=\"address\" placeholder=\"address\"\r\n");
      out.write("                        value=\"서울특별시\" />\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                     <input type=\"email\" class=\"form-control form-control-user\"\r\n");
      out.write("                        name=\"addressVO.addressDetail\" id=\"addressDetail\"\r\n");
      out.write("                        placeholder=\"addressDetail\" value=\"1010\" />\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("               <label for=\"exampleFormControlInput1\" class=\"form-label\">Cards</label>\r\n");
      out.write("               <div class=\"col-lg-6\">\r\n");
      out.write("                  <div class=\"card mb-4 py-3 border-left-primary\">\r\n");
      out.write("                     <div class=\"card-body\">\r\n");
      out.write("                        번호 : <input type=\"text\" class=\"form-control form-control-user\"\r\n");
      out.write("                           name=\"cardVOList[0].no\" id=\"no1\" placeholder=\"no\" /> \r\n");
      out.write("                        유효년월 : <input type=\"date\" class=\"form-control form-control-user\"\r\n");
      out.write("                        name=\"cardVOList[0].validMonth\" id=\"validMonth1\" placeholder=\"validMonth\" />\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"card mb-4 py-3 border-left-primary\">\r\n");
      out.write("                     <div class=\"card-body\">\r\n");
      out.write("                        번호 : <input type=\"text\" class=\"form-control form-control-user\"\r\n");
      out.write("                           name=\"cardVOList[1].no\" id=\"no1\" placeholder=\"no\" /> \r\n");
      out.write("                        유효년월 : <input type=\"date\" class=\"form-control form-control-user\"\r\n");
      out.write("                        name=\"cardVOList[1].validMonth\" id=\"validMonth1\" placeholder=\"validMonth\" />\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("               <a href=\"#\" id=\"aSubmit\" class=\"btn btn-primary btn-icon-split\">\r\n");
      out.write("                  <span class=\"icon text-white-50\"> <i class=\"fas fa-flag\"></i>\r\n");
      out.write("               </span> <span class=\"text\">요청파라미터Go</span>\r\n");
      out.write("               </a>\r\n");
      out.write("            </div>\r\n");
      out.write("         </form>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
